### EXERCISE 1

Review operations on lists (_adding/removing_ elements, _slicing_, _sorting_, etc.). Illustrate their usage on a list of your choice.

In [6]:
# YOUR CODE HERE:
list_op = [] #empty set
list_op.extend([True, "hello"]) # at multiple elements of different types
print(list_op)
list_op.append("at the end") # append at end of list
print(list_op)
popped = list_op.pop(0) # remove an element at position and returns its
print(popped)
print(list_op)
list_op.remove("hello") # remove instance of element
print(list_op)
list_op.append(False)
list_op.append(3)
list_op.append(3.1)
print(list_op)
print(len(list_op)) # returns length of list
print(list_op[:]) #slice from beginning to end
print(list_op[1:]) #slice from index one to end
print(list_op[:2]) #slice from start to index 2
# list_op.sort() unsupported operation since a bool and str in list
list_op.remove(False)
list_op.remove("at the end")
list_op.sort()
print(list_op)

[True, 'hello']
[True, 'hello', 'at the end']
True
['hello', 'at the end']
['at the end']
['at the end', False, 3, 3.1]
4
['at the end', False, 3, 3.1]
[False, 3, 3.1]
['at the end', False]
[3, 3.1]

### EXERCISE 2

Review operations on sets (like _intersection_ or _pop_) using the table https://wesmckinney.com/book/python-builtin.html#tbl-table_set_operations and illustrate usage of at least 3 of them for a set of your choice.

In [7]:
# YOUR CODE HERE:
set_op = set([2,2,3,3,1,1])
print(set_op)
set_op.add(4) # adding elements to set
set_op.add(0)
set_op.add(3)
print(set_op)
set_copy = set_op.copy() # making a copy
set_op.pop() # removing an element of set
set_op.pop()
set_op.pop()
print(set_op)
print(set_copy.intersection(set_op)) # insersection of the two sets
print(set_copy.issubset(set_op)) # t or f if subset of set
print(set_op.issubset(set_copy))

{1, 2, 3}
{0, 1, 2, 3, 4}
{3, 4}
{3, 4}
False
True

### EXERCISE 3

Write a Python program to concatenate a tuple to a string.

In [8]:
# YOUR CODE HERE:
your_tuple = ("replace","words","to","test")
your_str = ""
for i in your_tuple:
  your_str += i + " "
print(your_str)

replace words to test

### EXERCISE 4

Write a Python program to a string of comma-separated values into a tuple

In [9]:
# YOUR CODE HERE:
comma_str = "More,words,to,test" #string values
str_tuple = tuple(comma_str.split(","))
comma_str_ints = "2,3,4,5" #int values
new_int_list = []
for i in comma_str_ints.split(","):
  new_int_list.append(int(i))
int_tuple = tuple(new_int_list)
print(str_tuple)
print(int_tuple)

('More', 'words', 'to', 'test')
(2, 3, 4, 5)

### EXERCISE 5

Write a Python program to check if all values in a list are **different**

In [10]:
# YOUR CODE HERE:
def check_list_uniqueness(test_list):
  unique = True
  for item in test_list:
    amount = test_list.count(item) #counts the count of each element
    if amount > 1 :
      unique = False
  return unique
unique_list = [1,2,3,4]
non_unique_list = [1,2,2,3]
print(check_list_uniqueness(unique_list))
print(check_list_uniqueness(non_unique_list))

True
False

### EXERCISE 6

Write a Python program calculate the product, multiplying all the numbers of a given tuple.

Original Tuple:
(4, 3, 2, 2, -1, 18)
Product: -864

Original Tuple:
(2, 4, 8, 8, 3, 2, 9)
Product: 27648


Original Tuple:
(1, "Two", 3, "Four", 5)
Product: 15

In [11]:
# YOUR CODE HERE:
# using https://www.geeksforgeeks.org/python-convert-numeric-words-to-numbers/ for dict
word_dict = {
    'One': 1,
    'Two': 2,
    'Three': 3,
    'Four': 4,
    'Five': 5,
    'Six': 6,
    'Seven': 7,
    'Eight': 8,
    'Nine': 9,
    'Zero': 0
}

def product_from_tuple(hopefully_int_tuple):
  product = 1
  for number in hopefully_int_tuple:
    if word_dict.get(number) is None: # should be (if number is int) with no else
      product *= number
    else:
      product *= word_dict[number]
  return product

# not until I saw what was supposed to come out that you wanted just the ints
first_tuple = (4, 3, 2, 2, -1, 18)
second_tuple = (2, 4, 8, 8, 3, 2, 9)
third_tuple = (1, "Two", 3, "Four", 5)
print(f"Original Tuple:{first_tuple} Product:{product_from_tuple(first_tuple)}")
print(f"Original Tuple:{second_tuple} Product:{product_from_tuple(second_tuple)}")
print(f"Original Tuple:{third_tuple} Product:{product_from_tuple(third_tuple)}")

Original Tuple:(4, 3, 2, 2, -1, 18) Product:-864
Original Tuple:(2, 4, 8, 8, 3, 2, 9) Product:27648
Original Tuple:(1, 'Two', 3, 'Four', 5) Product:120

### EXERCISE 7
Write a script to:

* Print out the numbers from 1 to 20 but replacing numbers with 'Fizz' if divisible by 3, 'Buzz' if divisible by '5', and 'FizzBuzz' if divisible by 3 and 5.

Hint: the 'mod' operator, denoted %, is used to check divisibility. Example: 10 % 2 == 0.

In [12]:
# YOUR CODE HERE:
for i in range(1,21):
  if i % 3 == 0 and i % 5 == 0:
    print("FizzBuzz")
  elif i % 3 == 0:
    print("Fizz")
  elif i % 5 == 0:
    print("Buzz")
  else:
    print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz

### EXERCISE 8

Write a program to:
1. Generate a random number (kept secret from the user) using random.randint(0, 32)
2. Prompt the user "Guess a number" and record their input.
3. Tell them if they were correct, too high, or too low.

BONUS POINTS: limit the number of guesses to 5.

In [13]:
# YOUR CODE HERE:
import random
secret = random.randint(0, 32)
trys = 5
guess = int(input(f"Guess the secret number between 0 and 32, you have {trys} trys left: "))
while guess != secret and trys != 1:
  trys -= 1
  if guess > secret:
    print("Your guess is too high!")
  else:
    print("Your guess is too low!")
  guess = int(input(f"Guess the secret number between 0 and 32, you have {trys} trys left: "))

if guess == secret:
  trys -= 1
  print(f"The secret number was {secret}, you guessed it in {5-trys} trys!")
else:
  print(f"The secret number was {secret}, you ran out of trys!")

ValueError: invalid literal for int() with base 10: ''

### EXERCISE 9

Write a program that stores information about several European countries and their capital cities and conducts a quiz for the user: ask for a capital of a randomly selected country and validate the provided answer.

BONUS POINTS: Repeat 5 times and calculate the score

In [ ]:
europe = {
  "Austria": "Vienna",
  "Belgium": "Brussels",
  "Bulgaria": "Sofia",
  "Croatia": "Zagreb",
  "Cyprus": "Nicosia",
  "Czech Republic": "Prague",
  "Denmark": "Copenhagen",
  "Estonia": "Tallinn",
  "Finland": "Helsinki",
  "France": "Paris",
  "Germany": "Berlin",
  "Greece": "Athens",
  "Hungary": "Budapest",
  "Ireland": "Dublin",
  "Italy": "Rome",
  "Latvia": "Riga",
  "Lithuania": "Vilnius",
  "Luxembourg": "Luxembourg City",
  "Malta": "Valleta",
  "Netherlands": "Amsterdam",
  "Poland": "Warsaw",
  "Portugal": "Lisbon",
  "Romania": "Bucharest",
  "Slovakia": "Bratislava",
  "Slovenia": "Ljubljana",
  "Spain": "Madrid",
  "Sweden": "Stockholm",
}

In [ ]:
score = 0
for guesses in range(5):
  country = random.choice(list(europe.keys()))
  capital = europe[country]
  guess = input(f"What is the capital of {country}? ")
  if guess.lower() == capital.lower():
    print(f"Correct, the capital of {country} is {capital}.")
    score += 1
  else:
    print(f"Incorrect, the capital of {country} is {capital}.")
print(f"Your score was {score} out of 5")

What is the capital of Denmark? copenhagen
Correct, the capital of Denmark is Copenhagen.
What is the capital of Lithuania? vilnius
Correct, the capital of Lithuania is Vilnius.
What is the capital of Malta? test
Incorrect, the capital of Malta is Valleta.
What is the capital of Ireland? test
Incorrect, the capital of Ireland is Dublin.
What is the capital of Italy? test
Incorrect, the capital of Italy is Rome.
Your score was 2 out of 5

### EXERCISE 10

Develop a data structure for the following _Student_ object:

_Student_
* ID
* First name
* Last name
* Address
    * Number
    * Street
    * City
    * Country
    * Postcode
    * Coordinates
        * Longitude
        * Latitude
* Courses
    * Mathematics
        * Attendance
        * Final grade
    * Programming
        * Attendance
        * Final grade
    * Databases
        * Attendance
        * Final grade
    * IT
        * Attendance
        * Final grade

Using the developed data structure, compose a list fo 3-4 students. Use the composed list for:
1. Printing all student names as "Last name, First name"
2. Getting a list of all grades for a specified course
3. Checking that all ID are unique
4. Finding students with identical addresses
5. Finding a student with the smallest attendance (sum of course attendances)
6. Finding a student with the highest performance (sum of grades)
7. Removing one of the students (and re-printing the list)
8. Finding a pair of students with closest addesses (based on coordinates)

In [ ]:
# YOUR CODE HERE:
# not sure if a dictionary was the data structure you wanted
students = {
    "student_1": {
        "ID" : random.randint(0, 100000),
        "first_name": "Bob",
        "last_name": "Doe",
        "address": {
            "house_number": 1,
            "street": "first_street",
            "city": "New York",
            "country": "US",
            "postcode": 78201,
            "coordinates": {
                "longitude":  111.56539,
                "latitude":  -0.40837,
            }
        },
        "courses": {
            "mathematics": {
                "attendance": random.randint(0, 100),
                "final_grade": random.randint(0, 10)
            },
            "programming": {
                "attendance": random.randint(0, 100),
                "final_grade": random.randint(0, 10)
            },
            "databases": {
                "attendance": random.randint(0, 100),
                "final_grade": random.randint(0, 10)
            },
            "it": {
                "attendance": random.randint(0, 100),
                "final_grade": random.randint(0, 10)
            }
        }
    },
    "student_2": {
        "ID" : random.randint(0, 100000),
        "first_name": "Jane",
        "last_name": "Doe",
        "address": {
            "house_number": 1,
            "street": "baznicas",
            "city": "riga",
            "country": "LV",
            "postcode": 78201,
            "coordinates": {
                "longitude": 2.78008,
                "latitude": 42.07282,
            }
        },
        "courses": {
            "mathematics": {
                "attendance": random.randint(0, 100),
                "final_grade": random.randint(0, 10)
            },
            "programming": {
                "attendance": random.randint(0, 100),
                "final_grade": random.randint(0, 10)
            },
            "databases": {
                "attendance": random.randint(0, 100),
                "final_grade": random.randint(0, 10)
            },
            "it": {
                "attendance": random.randint(0, 100),
                "final_grade": random.randint(0, 10)
            }
        }
    },
    "student_3": {
        "ID" : random.randint(0, 100000),
        "first_name": "John",
        "last_name": "Doe",
        "address": {
            "house_number": 1,
            "street": "first_street",
            "city": "New York",
            "country": "US",
            "postcode": 78201,
            "coordinates": {
                "longitude": -98.45610,
                "latitude": 39.52274,
            }
        },
        "courses": {
            "mathematics": {
               "attendance": random.randint(0, 100),
                "final_grade": random.randint(0, 10)
            },
            "programming": {
                "attendance": random.randint(0, 100),
                "final_grade": random.randint(0, 10)
            },
            "databases": {
                "attendance": random.randint(0, 100),
                "final_grade": random.randint(0, 10)
            },
            "it": {
              "attendance": random.randint(0, 100),
                "final_grade": random.randint(0, 10)
            }
        }
    },
}

In [ ]:
# Printing all student names as "Last name, First name"
for i in students:
  print(students[i]["last_name"], students[i]["first_name"])

Doe Bob
Doe Jane
Doe John

In [ ]:
# Getting a list of all grades for a specified course
desired_course = "programming"
grades = []
for i in students:
  grades.append(students[i]["courses"][desired_course]["final_grade"])
print(f"Grades for {desired_course} are {grades}")

Grades for programming are [10, 8, 10]

In [ ]:
# Checking that all ID are unique
id_unique_flag = True
ids = []
for i in students:
  ids.append(students[i]["ID"])
for id in ids:
  if ids.count(id) > 1:
    id_unique_flag = False
print(f"{id_unique_flag}, the ids are unique {ids}")

True, the ids are unique [93913, 60662, 54104]

In [ ]:
# Finding students with identical addresses (only with same street names)
names = []
for i in students:
  names.append(i)
for i in range(len(names)-1):
  comparing_address = students[names[i]]["address"]["street"]
  for j in range(i+1,len(names)):
    temp_address = students[names[j]]["address"]["street"]
    if comparing_address == temp_address:
      print(f"{names[i]} and {names[j]} have the same address at {temp_address}")

student_1 and student_3 have the same address at first_street

In [ ]:
# Finding a student with the smallest attendance (sum of course attendances)
courses = ["mathematics","programming","databases","it"]
lowest_attendance_student = ""
lowest_attendance = 10_000
for name in names:
  temp_total_attendance = 0
  for course in courses:
    temp_total_attendance += students[name]["courses"][course]["attendance"]
  if lowest_attendance > temp_total_attendance:
    lowest_attendance = temp_total_attendance
    lowest_attendance_student = name
  print(f"{name} has total attendance of {temp_total_attendance}")
print(f"{lowest_attendance_student} has smallest attendance of {lowest_attendance}")

student_1 has total attendance of 188
student_2 has total attendance of 303
student_3 has total attendance of 184
student_3 has smallest attendance of 184

In [ ]:
# Finding a student with the highest performance (sum of grades)
highest_performance_student = ""
highest_score = 0
for name in names:
  temp_total_score = 0
  for course in courses:
    temp_total_score += students[name]["courses"][course]["final_grade"]
  if highest_score < temp_total_score:
    highest_score = temp_total_score
    highest_performance_student = name
  print(f"{name} has total score of {temp_total_score}")
print(f"{highest_performance_student} has the highest score of {highest_score}")

student_1 has total score of 10
student_2 has total score of 26
student_3 has total score of 23
student_2 has the highest score of 26

In [ ]:
# Removing one of the students (and re-printing the list)
print(names)
names.pop(0)
print(names)

['student_1', 'student_2', 'student_3']
['student_2', 'student_3']

In [ ]:
# guidance from https://stackoverflow.com/questions/19412462/getting-distance-between-two-points-based-on-latitude-longitude
import geopy.distance

In [ ]:
names = []
for i in students:
  names.append(i)

In [ ]:
from os import close
# Finding a pair of students with closest addesses (based on coordinates)
coords = []
for name in names:
  lat = students[name]["address"]["coordinates"]["latitude"]
  lon = students[name]["address"]["coordinates"]["longitude"]
  coords.append((lat,lon))
print(coords)

closest_address_students = ""
closest_address_distance = 100_000_000
for i in range(len(coords)-1):
  comparing_coord = coords[i]
  for j in range(i+1, len(coords)):
    temp_distance = geopy.distance.distance(coords[i],coords[j]).km
    if closest_address_distance > temp_distance:
      closest_address_distance = temp_distance
      closest_address_students = f"{names[i]} and {names[j]}"
print(f"{closest_address_students} are the closest address based on coordinates with {closest_address_distance} km")

[(-0.40837, 111.56539), (42.07282, 2.78008), (39.52274, -98.4561)]
student_2 and student_3 are the closest address based on coordinates with 7986.863589411175 km

### EXERCISE 11

Develop a data structure for storing the graph data below:
<img src="https://raw.githubusercontent.com/DmitryPavlyuk/python-da/main/week2/img/city_graph.png">

Extend the data with population of Latvian cities: https://en.wikipedia.org/wiki/List_of_cities_and_towns_in_Latvia

Use the composed data structure for:
1. Listing all cities, ordering them by population
2. Listing all cities directly connected to Riga, ordering them by distance
3. Finding a closiest city directly cinnected to Daugavpils

In [20]:
# YOUR CODE HERE:
cities_info = {
    "Ventspils" : {
        "population": 33_053,
        "connected_cities" : {"Liepaja": 188, "Jelgave": 176, "Jurmala": 154},
        "distance_to_Daugavpils" : 176 + 230
     },
     "Liepaja" : {
        "population": 67_335,
        "connected_cities" : {"Ventspils": 118, "Jelgave": 182, "Jurmala": 192},
        "distance_to_Daugavpils" : 182 + 230
     },
     "Jurmala" : {
        "population": 50_842,
        "connected_cities" : {"Ventspils": 154, "Liepaja": 192, "Jelgava": 45, "Riga": 38},
        "distance_to_Daugavpils" : 45 + 230
     },
     "Jelgava" : {
        "population": 55_384,
        "connected_cities" : {"Ventspils": 174, "Liepaja": 182, "Jurmala": 45, "Riga": 45, "Daugavapils": 230},
        "distance_to_Daugavpils" : 230
     },
     "Riga" : {
        "population": 614_987,
        "connected_cities" : {"Valmiera": 107, "Jelgave": 45, "Jurmala": 38, "Jekabpils": 140},
        "distance_to_Daugavpils" : 140 + 89
     },
     "Jekabpils" : {
        "population": 21_179,
        "connected_cities" : {"Riga" : 140, "Valmiera" : 162, "Rezekne": 101, "Daugavpils": 89},
        "distance_to_Daugavpils" : 89
     },
     "Valmiera" : {
        "population": 22_408,
        "connected_cities" : {"Riga": 107, "Jekabpils": 162, "Rezekne": 1185},
        "distance_to_Daugavpils" : 185 + 89
     },
     "Rezekne" : {
        "population": 26_805,
        "connected_cities" : {"Valmiera": 185, "Jekabpils": 101, "Daugavpils": 89},
        "distance_to_Daugavpils" : 89
     },
     "Daugavpils" : {
        "population": 79_299,
        "connected_cities" : {"Rezekne": 89, "Jekabpils": 89, "Jelgava": 230},
        "distance_to_Daugavpils" : 0
     }
    
}

#still not sure if this is what you want

### EXERCISE 12

Develop a data structure for storing the hierachical information of used cars:

Brand -> Model -> Car (year, price)

(1 brands, 2-3 models under each brand, 2-3 cars under each model).

Fill the structure with real data from a public source - e.g., http://www.ss.lv

In [10]:
# YOUR CODE HERE:
used_cars = {
    "Audi": {
          "A6" : {
              "Audi A6 Quattro": {
                "year" : 2020,
                "price" : 39_990
              },
              "Audi A6, Facelift, S-Line": {
                "year" : 2016,
                "price" : 21_990
              }
          },
          "A4" : {
              "Audi A4 S-Line": {
                "year" : 2008,
                "price" : 7_100
              },
              "Audi A4 2.0Tdi 105 kW automāts": {
                "year" : 2009,
                "price" : 7_750
              }
          }
      }
  }